<%@ taglib prefix="s" uri="/struts-tags" %>
<%@ taglib uri="/aps-core" prefix="wp" %>
<%@ taglib uri="/apsadmin-core" prefix="wpsa" %>
<%@ taglib prefix="wpsf" uri="/apsadmin-form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="wp" uri="/aps-core" %>

<!--List of all available metatags-->
<script>
    $(function () {
        var availableTags = [
            "keywords",
            "description",
            "subject",
            "copyright",
            "language",
            "robots",
            "revised",
            "abstract",
            "topic",
            "summary",
            "Classification",
            "author",
            "designer",
            "copyright",
            "reply-to",
            "owner",
            "url",
            "identifier-URL",
            "directory",
            "category",
            "coverage",
            "distribution",
            "revisit-after",
            "Expires",
            "Pragma",
            "Cache-Control",
            "og:title",
            "og:type",
            "og:url",
            "og:image",
            "og:site_name",
            "og:description",
            "fb:page_id",
            "og:email",
            "og:phone_number",
            "og:fax_number",
            "og:latitude",
            "og:longitude",
            "og:street-address",
            "og:locality",
            "og:region",
            "og:postal-code",
            "og:country-name",
            "og:type",
            "og:points",
            "og:video",
            "og:video:height",
            "og:video:width",
            "og:video:type",
            "og:video",
            "og:video:type",
            "og:video",
            "og:video:type",
            "og:audio",
            "og:audio:title",
            "og:audio:artist",
            "og:audio:album",
            "og:audio:type",
            "google-analytics",
            "disqus",
            "uservoice",
            "mixpanel",
            "microid",
            "apple-mobile-web-app-capable",
            "yes",
            "apple-mobile-web-app-status-bar-style",
            "format-detection",
            "viewport",
            "Page-Enter",
            "Page-Exit",
            "mssmarttagspreventparsing",
            "X-UA-Compatible",
            "msapplication-starturl",
            "msapplication-window",
            "msapplication-navbutton-color",
            "application-name",
            "msapplication-tooltip",
            "msapplication-task",
            "tweetmeme-title",
            "blogcatalog",
            "csrf-param",
            "csrf-token",
            "apple-mobile-web-app-capable",
            "apple-mobile-web-app-status-bar-style",
            "format-detection",
            "viewport",
        ];
        $("#new_metatag").autocomplete({
            source: availableTags
        });
    });
</script>