package com.redhat.bpms.examples.mortgage;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * This class was automatically generated by the data modeler tool.
 */
@XmlRootElement
@org.kie.api.definition.type.Label(value = "Mortgage Application")
public class Application  implements java.io.Serializable {

static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "Validation Errors")
    @org.kie.api.definition.type.Position(value = 7)
    private java.util.List<com.redhat.bpms.examples.mortgage.ValidationError> validationErrors;

    @org.kie.api.definition.type.Label(value = "Mortgage Interest APR")
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.Double apr;

    @org.kie.api.definition.type.Label(value = "Mortgage Amount")
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.Integer mortgageAmount;

    @org.kie.api.definition.type.Label(value = "Applicant")
    @org.kie.api.definition.type.Position(value = 0)
    private com.redhat.bpms.examples.mortgage.Applicant applicant;

    @org.kie.api.definition.type.Label(value = "Mortgage Amortization")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.Integer amortization;

    @org.kie.api.definition.type.Label(value = "Down Payment")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Integer downPayment;

    @org.kie.api.definition.type.Label(value = "Property")
    @org.kie.api.definition.type.Position(value = 1)
    private com.redhat.bpms.examples.mortgage.Property property;

    @org.kie.api.definition.type.Label(value = "Appraisal")
    @org.kie.api.definition.type.Position(value = 2)
    private com.redhat.bpms.examples.mortgage.Appraisal appraisal;

    public Application() {
    }

    public Application(com.redhat.bpms.examples.mortgage.Applicant applicant, com.redhat.bpms.examples.mortgage.Property property, com.redhat.bpms.examples.mortgage.Appraisal appraisal, java.lang.Integer downPayment, java.lang.Integer amortization, java.lang.Integer mortgageAmount, java.lang.Double apr, java.util.List<com.redhat.bpms.examples.mortgage.ValidationError> validationErrors) {
        this.applicant = applicant;
        this.property = property;
        this.appraisal = appraisal;
        this.downPayment = downPayment;
        this.amortization = amortization;
        this.mortgageAmount = mortgageAmount;
        this.apr = apr;
        this.validationErrors = validationErrors;
    }



    public java.util.List<com.redhat.bpms.examples.mortgage.ValidationError> getValidationErrors() {
        return this.validationErrors;
    }

    public void setValidationErrors(  java.util.List<com.redhat.bpms.examples.mortgage.ValidationError> validationErrors ) {
        this.validationErrors = validationErrors;
    }

    public java.lang.Double getApr() {
        return this.apr;
    }

    public void setApr(  java.lang.Double apr ) {
        this.apr = apr;
    }

    public java.lang.Integer getMortgageAmount() {
        return this.mortgageAmount;
    }

    public void setMortgageAmount(  java.lang.Integer mortgageAmount ) {
        this.mortgageAmount = mortgageAmount;
    }

    public com.redhat.bpms.examples.mortgage.Applicant getApplicant() {
        return this.applicant;
    }

    public void setApplicant(  com.redhat.bpms.examples.mortgage.Applicant applicant ) {
        this.applicant = applicant;
    }

    public java.lang.Integer getAmortization() {
        return this.amortization;
    }

    public void setAmortization(  java.lang.Integer amortization ) {
        this.amortization = amortization;
    }

    public java.lang.Integer getDownPayment() {
        return this.downPayment;
    }

    public void setDownPayment(  java.lang.Integer downPayment ) {
        this.downPayment = downPayment;
    }

    public com.redhat.bpms.examples.mortgage.Property getProperty() {
        return this.property;
    }

    public void setProperty(  com.redhat.bpms.examples.mortgage.Property property ) {
        this.property = property;
    }

    public com.redhat.bpms.examples.mortgage.Appraisal getAppraisal() {
        return this.appraisal;
    }

    public void setAppraisal(  com.redhat.bpms.examples.mortgage.Appraisal appraisal ) {
        this.appraisal = appraisal;
    }

	@Override
	public String toString()
	{
		return "Application [validationErrors=" + validationErrors + ", apr=" + apr + ", mortgageAmount=" + mortgageAmount + ", applicant="
				+ applicant + ", amortization=" + amortization + ", downPayment=" + downPayment + ", property=" + property + ", appraisal="
				+ appraisal + "]";
	}




}
