package com.redhat.bpms.examples.mortgage;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.definition.type.Label(value = "Appraisal")
public class Appraisal  implements java.io.Serializable {

static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "Appraised Value")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Integer value;

    @org.kie.api.definition.type.Label(value = "Appraised Property")
    @org.kie.api.definition.type.Position(value = 0)
    private com.redhat.bpms.examples.mortgage.Property property;

    @org.kie.api.definition.type.Label(value = "Appraisal Date")
    @org.kie.api.definition.type.Position(value = 1)
    private java.util.Date date;

    public Appraisal() {
    }

    public Appraisal(com.redhat.bpms.examples.mortgage.Property property, java.util.Date date, java.lang.Integer value) {
        this.property = property;
        this.date = date;
        this.value = value;
    }



    public java.lang.Integer getValue() {
        return this.value;
    }

    public void setValue(  java.lang.Integer value ) {
        this.value = value;
    }

    public com.redhat.bpms.examples.mortgage.Property getProperty() {
        return this.property;
    }

    public void setProperty(  com.redhat.bpms.examples.mortgage.Property property ) {
        this.property = property;
    }

    public java.util.Date getDate() {
        return this.date;
    }

    public void setDate(  java.util.Date date ) {
        this.date = date;
    }

	@Override
	public String toString()
	{
		return "Appraisal [value=" + value + ", property=" + property + ", date=" + date + "]";
	}




}
