package com.redhat.bpms.examples.mortgage;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.definition.type.Label(value = "Property")
public class Property  implements java.io.Serializable {

static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "Sale Price")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer price;

    @org.kie.api.definition.type.Label(value = "Property Address")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String address;

    public Property() {
    }

    public Property(java.lang.String address, java.lang.Integer price) {
        this.address = address;
        this.price = price;
    }



    public java.lang.Integer getPrice() {
        return this.price;
    }

    public void setPrice(  java.lang.Integer price ) {
        this.price = price;
    }

    public java.lang.String getAddress() {
        return this.address;
    }

    public void setAddress(  java.lang.String address ) {
        this.address = address;
    }

	@Override
	public String toString()
	{
		return "Property [price=" + price + ", address=" + address + "]";
	}




}
